// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxatdvcskimnivxdusgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4YXRkdmNza2ltbml2eGR1c2dxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNDI0NjUsImV4cCI6MjA2MzgxODQ2NX0.X05BNzJChl1V90UGS70AXLjpZ9g25jYf9uDJgy0dWnM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);